name: spreeloop_crash_reporting
description: Package that provides methods for reporting crash in application based on firebase crashlytics.
version: 0.0.3
homepage: https://github.com/spreeloop/core-dart/tree/master/crash_reporting
issue_tracker: https://github.com/spreeloop/core-dart/issues
topics:
  - firebase
  - crashlytics
  - report
  - error

environment:
  sdk: ^3.1.5
  flutter: ^2.10.4

dependencies:
  flutter:
    sdk: flutter

  # Flutter plugin for Firebase Crashlytics.
  firebase_crashlytics: ^4.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
