name: spreeloop_database
description: "Spreeloop database package."
version: 0.0.11
homepage: https://github.com/spreeloop/core-dart/tree/master/database

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database
  # with live synchronization and offline support on Android and iOS.
  cloud_firestore: ^5.6.5

  # Flutter plugin for Firebase Cloud Storage, a powerful, simple,
  # and cost-effective object storage service for Android and iOS.
  firebase_storage: ^12.4.4

  # Package for logging debug and error messages.
  logging: ^1.0.1

  # Package for cross plateform file library (XFile).
  cross_file: ^0.3.2

  # Library to display and cache network images.
  cached_network_image: ^3.3.1

  # Library for configuring network images caching.
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
